spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

razorpay.key.id=rzp_test_SuuFjCHKouwJqa
razorpay.key.secret=ThWuTjQDls39S7N0jx5j8acN